### ISSUE TITLE
Communicate Status of macOS 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#113]
Since the departure of mac maintainer, the EASY install has not ben able to be updated to the current version. 
The last announcement was November and no guidance was provided for the point release. 

Until the new certs signing process is in place, easy install routers cannot receive updates.  

Communication to participants needs to be clear and concise about the status of the macOS installer. 
This includes : timeline for certs
Letting them know that it okay to stay on the version they have until that time. 
Options for updating if they prefer.

**Comment by eyedeekay** [comment]
The I2P Easy-Install Bundle for Mac has been experiencing stalled updates for the past 2 months due to the sudden departure of the maintainer. Unfortunately, there are many steps to the process of distributing an application to Apple users, and we need to complete each of them before we can release an Easy-Install update.

The currently failing step is also the final step, called "Notarization." In order to distribute an app to Apple users as a `.dmg` securely, the app must pass this notarization process. In order to submit an app for notarization, the developer must sign the app using a set of certificates, one for code signing, and one for signing the bundle itself. This signing must take place at specific points during the build process, before the final `.dmg` bundle which is distributed to the end users may be created. I2P is a complex application in this sense because it mixes different types of code, mixing code that runs on the JVM with platform-specific binary code. To put it simply, we don't know for sure which certificate needs to be used for each type of code, and when this signing must take place to produce a valid timestamp. The documentation on this point is fairly unhelpful and we have resorted to a process of trial-and-error and deduction to discover the correct combination of factors to produce a notarized bundle reliably.

Unfortunately, this leaves the timeline difficult to predict. We won't know we're done until we are able to clean up the build environment and follow the process end-to-end. However, we are down to only 4 errors during the notarization process from more than 50 during the first attempt, and may be nearing a successful notarization.

For the time being, it is recommended that existingn Easy-Install users delay updating and remain on `1.9.0` until we successfully notarize a bundle and deliver it to them.

Some potential I2P users may wish to use the "Classic" install process using Java for Mac and the `.jar` based installer.

If you prefer to update sooner, as an Easy-Install user one may update using a locally-produced development build. You may also switch to a jar based installer by uninstalling the Easy-Install bundle, removing the I2P configuration directory, and installing using Java for Mac and the `.jar` based installer.

**Comment by Shoalsteed** [comment]
The I2P Easy-Install Bundle for Mac has been experiencing stalled updates for the past 2 releases due to the departure of its maintainer. For the time being, it is recommended that existing Easy-Install users delay updating and remain on 1.9.0 until the development team can successfully notarize the application and resume automatic updates. The updates will happen immediately once this has happened. For now, 1.9.0 is stable and has known security issues.  

**The Notarization Process For MacOS** 
There are many steps in the process of distributing an application to Apple users.
In order to distribute an application as a .dmg securely, the application must pass a notarization process. In order to submit an application for notarization, a  developer must sign the application using a set of certificates that includes one for code signing, and one for signing the application itself. This signing must take place at specific points during the build process, before the final .dmg bundle which is distributed to the end users can be created. 

I2P Java is a complex application, and because of this it is a process of trial and error to match the types of code used in the application to Apple's certificates, and where the signing takes place to produce a valid timestamp.  It is due to this complexity that existing documentation for developers is falling short of helping the team understand the correct combination of factors that will result in successful notarization. 

It leaves the timeline for completing this process difficult to predict. We won't know we're done until we are able to clean up the build environment and follow the process end-to-end. The good news is that we are down to only 4 errors during the notarization process from more than 50 during the first attempt and can reasonably predict that it will be competed before or in time for the next release in April. 

**Options for New macOS I2P Installs and Updates**
New I2P participants can still download the Easy Installer for the macOS 1.9.0 software. It will receive updates no later than the next scheduled release in April. Updates to the latest version will become available as soon as notarization is successful.

The classic install options is also available. This will require downloading Java and the I2P software via the .jar based installer. 

Easy-Install users can update to that latest version using a locally-produced development build. 
There is also the option to uninstall the software, remove the I2P configuration directory and reinstall I2P using the .jar installer.

**Comment by eyedeekay** [comment]
Closable

**Comment by Shoalsteed** [comment]
Implemented and closed!
