### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#2]
https://github.com/Shoalsteed/UX/issues/22

Moving this here.

**Comment by luciewho** [comment]
**Conversation with UX researcher on another privacy tool, referred to as Nadine below**

**About the survey she sent out**
There is no survey that doesn’t track. The survey is open to all, not just privacy community. Investigative journalists and human rights defenders don’t have much time for privacy. Overall there is a strong need for privacy but people don’t have time to learn the tools. Don’t expect many differences but it will interesting to compare. 

**On how to get a hold of the right users to do research with**
A good starting point is if there is an established community on Reddit, Telegram, Signal groups. If you have any community support channels to get to real users. Made it easier to recruit people on reddit. Nadine posted a message on reddit saying "I’m conducting first user research, need participants." Did a diary study with 13 people who completed diary study for 10 days without payment, highly motivated people. Got the sense of who is using ____. There weren't actually the target user of ____. It is more of exploratory research, not so much usability, to understand their needs. But try to test something with them, even if they are not the actual users. 

Nadine also had mostly male, IT people from Reddit. Because our products are so technical. We need to fix the website. Need to make it more digestible. Email needs to function better. Even so tech people were complaining about usability. 

**Diary study** 
Second day - installation process
Third day - other apps they installed
Rest of the days - report any issues 
Work with your team and ask them - what do you all want to know?

**Did you ever interview with at-risk users such as activists or journalist?** 
No. I don’t know whether they exist. I did a lot of journalists/activists but they weren’t ____ users. Didn’t have opportunity to meet a human rights defender that uses ____. I don’t think they use it because ____ is only on Google Pixel and Xiaomi. Those phones are not across the globe. Talked to tech people and regular users that care about privacy. At risk users - not because they can’t or don’t want to, but don’t have time. People who really need to have a secure connection, they don’t have time to explore tools. They use WhatsApp because all their network is using that tool. Privacy has to happen in a network otherwise it’s useless. 

NGO or digital privacy org can help connect at-risk users with privacy tools. 

People that use our tools have a lot of time, it’s ironic. Lots of time to explore. 
The threat for them is not “real.” Guy that encrypts email to ask me two questions that don’t need to be encrypted. Whereas journalist in Mexico really should be encrypting and they are not. 

**Marketing/communication**
Project might need to improve the “marketing” the right way of communicating in the right way. “Publicity” to reach the right people. Very important for all open source privacy. In the end, all tech people reach these tools because they search all day for tools. That’s their job.

Nadine wants to see some co-design with communities. Hard to find people to collab with. Really want a journalist in the field using ___ for a few days and give feedback. More networking and collaboration with journalists. Not only get amazing feedback from users, but it makes publicity - someone is trying it and could be related to the work they’re doing and seen in practice/context. Establish network with orgs working with people at risk.

MatterMost - internet freedom festival. Online community across the globe. Ask for help there as well. Oriented towards privacy community.

**Signal is successful**
Signal - easiest one to use. That’s why. It only has one task — texting. The agenda is very clear, the product is very clear. It performs a few things, that’s it. With I2P, ____ - entire system, not only one system. There are many more complex design flows to consider. Signal is a straight-forward offering. Matched with good usability, user friendly. 

Common people don’t care about “privacy” — they say they care but their behaviors do not match. Signal is easy so they can do it. Their marketing is not around being private/secure. They don’t put the emphasis, they don’t even sell it. It's mainstream right now. Signal has very few flows and design to work on. ____/I2P have really small teams, can’t work on everything, have to prioritize. Need more people!

**About technical users/contributors** 
They are volunteers from big tech and help with open source projects. Nadine's observation – only want to do what they want, when they want. When you have to work with volunteers, it will take months that could be done in a week. Motivation is different. They do this work so they feel less guilty that they work with tech giants. Not actually thinking to improve the project for real. When not getting paid, they don’t see it as a job. See it as entertainment, ego, etc. Need more people hired to help them improve the project. Contributors also very tech-y. Open-source community needs more people that are not volunteers but people that get paid.

**About Tor**
Nadine’s research shows — journalists use it very minimally and for very specific things, not their main tool. Nadine’s guess is that people who use Tor and super private software, it’s mostly tech people and male. Human rights defenders said hard to find things in Tor and hard to use.

**Comment by eyedeekay** [comment]
... What does Signal market, if not privacy/security?

**Comment by Shoalsteed** [comment]
I think that the comment about people not caring about privacy means that unless the tool makes it very easy to use they might not engage in using tools. That may be seen as " not caring" by people who can use the tools or are familiar with them.  Signal markets privacy, but it is also does a specific thing really well is a very easy to use way.  People engage in privacy sometimes only if it does not have a barrier to entry / use or one that is not difficult.
