### ISSUE TITLE
I2P In Private Browsing

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#29]
Usability Review 
https://github.com/eyedeekay/I2P-in-Private-Browsing-Mode-Firefox

**Comment by luciewho** [comment]
- UI and visual - no sense of visual hierarchy and what to focus on. 
- The search bar in the modal has text that doesn’t make sense. Search legwork.i2p? Or is it supposed to be searching the homepage because the copy is “Homepage:” before the search bar. Also not sure what I’m supposed to search for. Does it behave like a google search? Anytime I search and put in words like “email” “cat” “torrent” I get the same error page (cannot be found in Address Book)
- “Create” makes me think that I’m creating an i2p site. Something visually engaging such as icons for ‘new tab’ or ‘close’. Make it emulate what opening/closing tabs are like on the browser.
- The new tab that pops up when clicking “create” would be better if it could look like the homepage. Currently just matches what my clearnet Firefox tab looks like but is purple color scheme instead of white. But I can’t do anything such as use the search bar or click any of the links because it’s for clearnet - wasted potential.
- Copy needs consistency - hidden email/email when it should be called Susimail
- More obvious menu bar in the modal would be better
- Don’t know how to browse I2P. I have to be given a URL or just guess. Is there some sort of database or dashboard of all existing I2P websites that are available for public view?

**Comment by Shoalsteed** [comment]
<img width="555" alt="Screen Shot 2022-02-07 at 5 10 20 PM" src="https://user-images.githubusercontent.com/50714166/152880706-d4144c8b-239e-4dcc-864b-8664e1b1c535.png">

- remove icons. The Search icon does not work, and having an icon called "Download" is confusing. This space should be reserved for the name / description of the extension. 

- I2P In Private Browsing: this extension may have started out as an *out of the box* option for a configureless option for the browser, but it now has added functionality. 
"I2P Connect" may be a direction to take to consider a more consumer friendly name for the extension. "zero configuration access to the I2P network and secure application access" 
- the section called Home Page is confusing, I have tried several times to put a query in the box and hit submit, but nothing happens? Also, seeing "legwork is confusing. What am I using?
- "Proxy is ready" and "your bowser is now set up to use I2P" - do these mean the same thing? Could this be simplified too "You are connected to the I2P network?"
- the green ready indicator does not stay on for me.

**Comment by Shoalsteed** [comment]
<img width="542" alt="Screen Shot 2022-02-07 at 5 10 26 PM" src="https://user-images.githubusercontent.com/50714166/152882080-ae415260-19e9-4629-a9ac-98da8890f834.png">

Rename this section to Browsing Preferences?
*create* should say *open new window*
close all windows 
Disable History option

**Comment by Shoalsteed** [comment]
<img width="537" alt="Screen Shot 2022-02-07 at 5 10 33 PM" src="https://user-images.githubusercontent.com/50714166/152882327-ae3eb69c-70b7-4e83-8b49-d2f25a98a714.png">

For the email and bitorrent options, the actual name of the application should be used ie Snark.
the copy " these applications work directly with I2P...."
This is actually a way to access the applications that ship with the Java software, so the copy should reflect that for creating trust. 
<img width="1118" alt="Screen Shot 2022-02-07 at 5 31 03 PM" src="https://user-images.githubusercontent.com/50714166/152883245-723ff4d3-d840-4ba6-8657-fcd5857bae61.png">

the Help link leads to this page?

**Comment by Shoalsteed** [comment]
<img width="1175" alt="Screen Shot 2022-02-07 at 5 29 11 PM" src="https://user-images.githubusercontent.com/50714166/152883093-f052be05-3c8a-4a8a-a5b4-bccd72fc0562.png">

can the extension serve a home page instead of a modal?

**Comment by Shoalsteed** [comment]
<img width="423" alt="Screen Shot 2022-02-07 at 5 34 17 PM" src="https://user-images.githubusercontent.com/50714166/152883583-f19ce257-31bc-43bc-b962-b10abfacb1d1.png">
I noticed that on the extension page itself, that there is a tag line that says "your browser is now set up to use I2P" 
Does this have different meaning than when it appears on the modal?

**Comment by luciewho** [comment]
> <img alt="Screen Shot 2022-02-07 at 5 10 20 PM" width="555" src="https://user-images.githubusercontent.com/50714166/152880706-d4144c8b-239e-4dcc-864b-8664e1b1c535.png">
> 
> * remove icons. The Search icon does not work, and having an icon called "Download" is confusing. This space should be reserved for the name / description of the extension.
> * I2P In Private Browsing: this extension may have started out as an _out of the box_ option for a configureless option for the browser, but it now has added functionality.
>   "I2P Connect" may be a direction to take to consider a more consumer friendly name for the extension. "zero configuration access to the I2P network and secure application access"
> * the section called Home Page is confusing, I have tried several times to put a query in the box and hit submit, but nothing happens? Also, seeing "legwork is confusing. What am I using?
> * "Proxy is ready" and "your bowser is now set up to use I2P" - do these mean the same thing? Could this be simplified too "You are connected to the I2P network?"
> * the green ready indicator does not stay on for me.

What does the "1.28" mean? Does it need to be there? Is it the version number? Can it be place in a more discreet place and with more language/context around it to make it more meaningful?

Agreed that the "Browse" and "Download" links with icons are confusing. 
I thought I already downloaded the extension, isn't that it? Is there more to download? 
What is the difference between Browse and the Homepage/legwork search box?

Also not sure what I'm supposed to search for. Should I treat it like a Google search box? Is it supposed to show a list of links/pages based on keyword(s) like Google does?

**Comment by luciewho** [comment]
> <img alt="Screen Shot 2022-02-07 at 5 10 26 PM" width="542" src="https://user-images.githubusercontent.com/50714166/152882080-ae415260-19e9-4629-a9ac-98da8890f834.png">
> 
> Rename this section to Browsing Preferences? _create_ should say _open new window_ close all windows Disable History option

I am not sure about "Preferences" because that makes it sound like extraneous details, when "Open a new window" and "Close Windows" are pretty important functions. (The Disable History is more like Preferences). 
"Control Panel" could make sense. It should be a visual UI button, not just a text link. That gives it visual hierarchy/indicates an action is to be performed. And it should be near the top, maybe even before the search box.

**Comment by luciewho** [comment]
> <img alt="Screen Shot 2022-02-07 at 5 29 11 PM" width="1175" src="https://user-images.githubusercontent.com/50714166/152883093-f052be05-3c8a-4a8a-a5b4-bccd72fc0562.png">
> 
> can the extension serve a home page instead of a modal?

I think that would be a huge plus. These functions aren't usable within the Extension. Apply the Homepage here.

**Comment by luciewho** [comment]
<img width="959" alt="Screen Shot 2022-02-25 at 10 02 20 AM" src="https://user-images.githubusercontent.com/6728799/155764866-72ede36b-d686-42cd-bdde-b6e0e73fdc32.png">

Quick stab at a redesign of the extension pop-out modal. Keep in mind, this is more to see how the visual design could be improved, but does not take into account of an improved UX and flow. There are still many lingering questions such as: 

Where and what does the search box search? Does it search for pages or torrents within i2p or perhaps the router? 
As of now, it looks like the "Homepage" link and "Create" link go to the same page (homepage). Seems redundant and one could be removed. Also, could just open and close tabs within the browser itself, why is there a need for "Create" and "Close All" within the modal?

When looking at the Homepage, some other questions came to mind:

Under the "Applications" section, there is a link to Router Console that says it directs to more applications. This is not an application, right? Makes it seem like an application within application?

A lot of the links in the modal and on the homepage (email, BitTorrent, hidden services manager, etc) can all be found on the Router Console. Why do they need to appear everywhere so many times? Why can't I just use the Router Console since it already has everything?
What is the purpose of the homepage and what function does it perform (especially if the Router Console already has the same information)?

**Comment by eyedeekay** [comment]
> <img alt="Screen Shot 2022-02-07 at 5 10 20 PM" width="555" src="https://user-images.githubusercontent.com/50714166/152880706-d4144c8b-239e-4dcc-864b-8664e1b1c535.png">
> 
>     * remove icons. The Search icon does not work, and having an icon called "Download" is confusing. This space should be reserved for the name / description of the extension.
>

Search icon works fine for me, and I'm not removing the download button. I'll change it to a name that works better for people, but I'm not going to remove it, that page houses significant extension functionality, it's where the UX for the bittorrent integration happens. The reason Download got it's own page in the actionpanel is because it's that important and complex on it's own.

>     * I2P In Private Browsing: this extension may have started out as an _out of the box_ option for a configureless option for the browser, but it now has added functionality.
>       "I2P Connect" may be a direction to take to consider a more consumer friendly name for the extension. "zero configuration access to the I2P network and secure application access"
> 

Rebranding it is going to be ugly but I'll go through it.

>     * the section called Home Page is confusing, I have tried several times to put a query in the box and hit submit, but nothing happens? Also, seeing "legwork is confusing. What am I using?
> 

legwork.i2p is an in-I2P search engine, if you visit it once through an address helper it will work but until you visit it at least once it won't. There is no way to fix this unless @mhatta goes through the process of becoming includes in the default hosts.txt file which comes with all I2P installs. Thusfar he has been unable to do so. I'm not taking the search engine out of the extension, though.

>     * "Proxy is ready" and "your bowser is now set up to use I2P" - do these mean the same thing? Could this be simplified too "You are connected to the I2P network?"

No, they don't, and no, they can't. Proxy readiness happens after you're connected to the I2P network, and browser readiness is entirely independent from both. That's a huge part of the problem, none of these components started out connected to eachother. Your browser can be set up to use I2P before the proxy is ready and before I2P is running. The browser needs a way to determine both.

> 
>     * the green ready indicator does not stay on for me.

This bug is resolved in new versions but the indicator is entirely textual now.

**Comment by eyedeekay** [comment]
> > <img alt="Screen Shot 2022-02-07 at 5 10 20 PM" width="555" src="https://user-images.githubusercontent.com/50714166/152880706-d4144c8b-239e-4dcc-864b-8664e1b1c535.png">
> > 
> > * remove icons. The Search icon does not work, and having an icon called "Download" is confusing. This space should be reserved for the name / description of the extension.

If you mean the magnifying glass icon next to "Browse," Click the "Download" button, then click the "Browse" button. See how it switches between the 2 pages, the main page and the page that monitors bittorrent downloads? They are tabs, and they're there because I can't add 2 buttons to the Firefox menu in a single extension. There might be a better way to do this but it's doing exactly what it's supposed to.

> What does the "1.28" mean? Does it need to be there? Is it the version number? Can it be place in a more discreet place and with more language/context around it to make it more meaningful?
> 

It's a version number. I'd just as soon remove it but it was requested by a user that I add it.

> Agreed that the "Browse" and "Download" links with icons are confusing. I thought I already downloaded the extension, isn't that it? Is there more to download? What is the difference between Browse and the Homepage/legwork search box?
> 

Browse is a tab in the actionpanel that contains the homepage link(which opens the extension homepage in a new tab) and legwork search box, and the tab control panel, and the application links. It's the entire page, whereas the homepage link and the legwork search box are tiny components of the page.

> Also not sure what I'm supposed to search for. Should I treat it like a Google search box? Is it supposed to show a list of links/pages based on keyword(s) like Google does?

More or less, it's pointed at a Yacy instance running inside of I2P by @mhatta. The details of the service are outside my control, it's not a part of the extension.

**Comment by eyedeekay** [comment]
> <img alt="Screen Shot 2022-02-07 at 5 29 11 PM" width="1175" src="https://user-images.githubusercontent.com/50714166/152883093-f052be05-3c8a-4a8a-a5b4-bccd72fc0562.png">
> 
> can the extension serve a home page instead of a modal?

Feature added, not getting rid of the modal because a home page is inherently optional and cannot be made non-optional. The modal is the only way to work for everybody.

**Comment by Shoalsteed** [comment]
Lots of effort went into trying to provide constructive feedback on issues with the UX of this extension. 
I am not clear if there is way forward given the responses.
