### ISSUE TITLE
New to I2P, where do I start?

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#47]
https://www.reddit.com/r/i2p/comments/utixsd/new_to_i2p_where_do_i_start/

I come across this question often. I always wonder what it means. 
_What do you want to do? What are your expectations?_ 

First, I feel that the issue comes from conflating the Java software with the network itself. If we look at the Java software, we see examples of the versatilities for network use and some usable applications. 

What the I2P network does not do enough of is promote application development. The applications that exist do not pattern match to common usability and are not cross platform due to complexity with working with OSX for example.  So people who are looking too perhaps find content, generate content, promote themselves or socialize encounter issues in many if not all of these areas. 

Community efforts become lost since there is no centralized place to find them. There are no standards either for developing applications, or promotion or participating in testing.

**Comment by eyedeekay** [comment]
Latest approach on my part is to try and encourage specificity by asking questions, i.e.

1.  Do you have a A) specific threat model or B) is your primary goal to "explore" the anonymous network?
2.  Do you want to A) continue computing as you currently do without changing your workflow much or B) change your workflow in order to accommodate a threat model?
