### ISSUE TITLE
Why Trust Open Source

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#48]
How do we trust model w/out code / sigs ? 
ie, if I cannot write or audit code, how does having it accessible hep me trust model? 
How can we describe the benefits of free open source without dependencies / bias?

**Comment by eyedeekay** [comment]
>  ie, if I cannot write or audit code, how does having it accessible hep me trust model?

If the code is not accessible, not only can *you* not audit the code, but you can't ask anyone else to either. In fact, in many cases, attempting to obtain the source code of the program is literally a crime. It begs the question: what do these proprietary software vendors have to hide from me? Why do they [treat users as the enemy](https://cheapskatesguide.org/articles/pluton.html)? It's not so much that you *can* trust open source software for any single reason(although there are good ones), it's that the evidence would suggest that it's staggeringly irresponsible to trust a software company that's deliberately hiding what it does from you with protecting your privacy when they could instead be monetizing your data. There are basically no good actors left. Without open source, you are the product, 100% of the time, whether you're paying or not. With it, it can still go either way.

Besides that, open source enables other people to simply *compile* the software, which is a much lower barrier, and gives it an advantage in authentication that non-free software can never actually have. This is because if you're a developer of an open source program you can prescribe that it be built in a specific way when you release it, making it predictable or "deterministic." That means that other people, who don't necessary know how your code works, can set up a build environment and compile it per your release instructions and end up with **exactly the same file**. You can then compare the file you downloaded with the file you generated, and have a [way of determining that the binary you received corresponds to the source which was published](https://wiki.mozilla.org/Security/Binary_Transparency). In fact, you can [build a network of open-source computers that continuously do this to eachother in order to help learn about how to prevent supply chain attacks](https://reproducible-builds.org/citests/). This does not exist in the world where you aren't allowed to use the source code of your applications.

**Comment by Shoalsteed** [comment]
https://devblogs.microsoft.com/premier-developer/the-food-truck-paradigm-why-should-i-trust-open-source-software/

**Comment by Shoalsteed** [comment]
blog post created.
